### PR TITLE
[73] Make Menu Bar responsive

### PR DESCRIPTION
**Pull request by PKhing**
## What did you do

- Make menu bar responsive
image

## Demo

- login with `casting4@gmail.com` and go to https://dev.modela.miello.dev/job/10/actor
- don't forget to check this page on actor side too (to ensure that I didn't mess something up)

### CODE REVIEW

**Comment by miello** [comment]
Should Header stick to navbar ?
image

image

**Comment by miello** [comment]
Can we add a little bit height here ? (2 - 3 px)

image

**Comment by PKhing** [comment]
Sorry for the hacky solution. It is hard to directly make a sticky div since the structure is not designed to support mobile design in the first place.

**Review by miello — APPROVED** [review]
Is this "Bad Smell" 😂

**Pull request merged**
